### ISSUE TITLE
Option is not defined

### ISSUE THREAD

**Issue by gkp-dev** [yisheng90/react-loading#17]
I put your skeleton component inside my nextJs application and it worked incredibly well but anytime I run my application at the beginning of the app it's said Option is not defined. And i don't know what it is.

**Comment by gkp-dev** [comment]
> 
> 
> I put your skeleton component inside my nextJs application and it worked incredibly well but anytime I run my application at the beginning of the app it's said Option is not defined. And i don't know what it is.

#

**Comment by bintangyoga** [comment]
Hi @gkp-dev, i'm having the same issue. Have you found the solution yet?
