### ISSUE TITLE
Safari shows red gradient for loading

### ISSUE THREAD

**Issue by HarshRajat** [yisheng90/react-loading#4]
Hey... first of all... really awesome work! Just what was needed for a project of mine :).

Coming to the point, safari shows reddish gradient when loading even when the color is specified. I am thinking the issue is this line of css: background-image: linear-gradient(90deg, rgba(255, 0, 0, 0), rgb(245, 245, 245), rgba(255, 0, 0, 0));
}

**Comment by yisheng90** [comment]
Hi @HarshRajat, thanks for the feedback. I have publish a fix for that. The issue should be revolved since v1.3.1.
